languaje: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - "12"

script:
  - npm install
  - npm run build

before_deploy:
  - npm install netlify-cli -g

deploy:
  provider: netlify
  dir: "dist/"
  site: $NETFLIFY_SITE
  auth: $NETLIFY_AUTH
  on:
    branche: main