languaje: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - "12"

script:
  - npm install
  - npm run test
  - npm run build

before_deploy:
  - npm install netlify-cli -g
deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=dist --prod
  on:
    branche: main

notifications:
  email:
    - matiasaravia52@gmail.com
